/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bindle_project.View;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ACER
 */
public class CartScreen extends javax.swing.JFrame {

    /**
     * Creates new form CartScreen
     */
    public CartScreen() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        JPanel panel = new JPanel();
        panel.add(new JLabel("Cart functionality not implemented."));
        JButton closeButton = new JButton("Close");
        closeButton.addActionListener(e -> dispose());
        panel.add(closeButton);

        add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cartItemsPanel = new javax.swing.JPanel();
        kafkaBookLabel = new javax.swing.JLabel();
        kafkaBookTitle = new javax.swing.JLabel();
        authorsName = new javax.swing.JLabel();
        increasingDecreasing = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        deleteLabel = new javax.swing.JLabel();
        wishlistLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kafkaBookTitle1 = new javax.swing.JLabel();
        kafkaBookTitle2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        labelLogoTitle = new javax.swing.JLabel();
        labelLogoSubTitle = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        labelSearchLogo = new javax.swing.JLabel();
        labelHeartIcon = new javax.swing.JLabel();
        labelCartIcon = new javax.swing.JLabel();
        labelShoppingCartText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cartItemsPanel.setLayout(null);

        kafkaBookLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/Kafka.png"))); // NOI18N
        cartItemsPanel.add(kafkaBookLabel);
        kafkaBookLabel.setBounds(0, 0, 120, 185);

        kafkaBookTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        kafkaBookTitle.setText("Metamorphosis");
        cartItemsPanel.add(kafkaBookTitle);
        kafkaBookTitle.setBounds(150, 20, 130, 30);

        authorsName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        authorsName.setText("By Franz Kafka");
        cartItemsPanel.add(authorsName);
        authorsName.setBounds(150, 50, 100, 17);

        increasingDecreasing.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        increasingDecreasing.setText("- 1 +");
        cartItemsPanel.add(increasingDecreasing);
        increasingDecreasing.setBounds(150, 160, 70, 30);

        priceLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        priceLabel.setText("NPR. 720");
        cartItemsPanel.add(priceLabel);
        priceLabel.setBounds(650, 30, 70, 17);

        deleteLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/Thrashcan.png"))); // NOI18N
        deleteLabel.setText("Remove");
        deleteLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cartItemsPanel.add(deleteLabel);
        deleteLabel.setBounds(460, 170, 90, 30);

        wishlistLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        wishlistLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/Bookmark.png"))); // NOI18N
        wishlistLabel.setText("Wishlist");
        cartItemsPanel.add(wishlistLabel);
        wishlistLabel.setBounds(570, 170, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/SallyRooney.png"))); // NOI18N
        cartItemsPanel.add(jLabel1);
        jLabel1.setBounds(0, 200, 120, 190);

        kafkaBookTitle1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        kafkaBookTitle1.setText("Metamorphosis");
        cartItemsPanel.add(kafkaBookTitle1);
        kafkaBookTitle1.setBounds(150, 20, 130, 30);

        kafkaBookTitle2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        kafkaBookTitle2.setText("Metamorphosis");
        cartItemsPanel.add(kafkaBookTitle2);
        kafkaBookTitle2.setBounds(150, 20, 130, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Intermezzo");
        cartItemsPanel.add(jLabel2);
        jLabel2.setBounds(150, 240, 100, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("By Sally Rooney");
        cartItemsPanel.add(jLabel3);
        jLabel3.setBounds(150, 260, 100, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("- 1 +");
        cartItemsPanel.add(jLabel4);
        jLabel4.setBounds(150, 360, 50, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/Thrashcan.png"))); // NOI18N
        jLabel5.setText("Remove");
        cartItemsPanel.add(jLabel5);
        jLabel5.setBounds(460, 360, 100, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/Bookmark.png"))); // NOI18N
        jLabel6.setText("Wishlist");
        cartItemsPanel.add(jLabel6);
        jLabel6.setBounds(570, 360, 80, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("NPR. 819");
        cartItemsPanel.add(jLabel7);
        jLabel7.setBounds(650, 260, 60, 20);

        jScrollPane1.setViewportView(cartItemsPanel);

        headerPanel.setLayout(null);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/BindleBook.png"))); // NOI18N

        labelLogoTitle.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelLogoTitle.setText("Bindle");

        labelLogoSubTitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLogoSubTitle.setText("Reselling academic and non academic books ");

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        labelSearchLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/SearchIcon.png"))); // NOI18N

        labelHeartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/Heart.png"))); // NOI18N
        labelHeartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHeartIconMouseClicked(evt);
            }
        });

        labelCartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/Cart.png"))); // NOI18N

        labelShoppingCartText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelShoppingCartText.setText("Shopping Cart (n)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelShoppingCartText)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLogoSubTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelLogoTitle)
                                        .addGap(53, 53, 53)
                                        .addComponent(labelSearchLogo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCartIcon)
                                .addGap(18, 18, 18)
                                .addComponent(labelHeartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelSearchLogo, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(labelLogoTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelHeartIcon)
                                        .addComponent(labelCartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelLogoSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelShoppingCartText)
                        .addGap(1, 1, 1)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void labelHeartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHeartIconMouseClicked

            // TODO add your handling code here:
    }//GEN-LAST:event_labelHeartIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorsName;
    private javax.swing.JPanel cartItemsPanel;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel increasingDecreasing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kafkaBookLabel;
    private javax.swing.JLabel kafkaBookTitle;
    private javax.swing.JLabel kafkaBookTitle1;
    private javax.swing.JLabel kafkaBookTitle2;
    private javax.swing.JLabel labelCartIcon;
    private javax.swing.JLabel labelHeartIcon;
    private javax.swing.JLabel labelLogoSubTitle;
    private javax.swing.JLabel labelLogoTitle;
    private javax.swing.JLabel labelSearchLogo;
    private javax.swing.JLabel labelShoppingCartText;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel wishlistLabel;
    // End of variables declaration//GEN-END:variables
}
