/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bindle_project.View;


import java.awt.event.ActionListener;

/**
 *
 * @author diyan
 */
public class UpdatePassword extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePassword
     */
    public UpdatePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NewPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        OldPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JPasswordField();
        Reset = new javax.swing.JButton();
        Show1 = new javax.swing.JButton();
        Show2 = new javax.swing.JButton();
        Show3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Change Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 77, 245, -1));

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 209, -1, -1));
        getContentPane().add(NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 206, 188, -1));

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Old Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 172, 79, -1));
        getContentPane().add(OldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 159, 189, 29));

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 250, -1, -1));
        getContentPane().add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 247, 188, -1));

        Reset.setBackground(new java.awt.Color(0, 102, 102));
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Reset");
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 301, 75, -1));

        Show1.setForeground(new java.awt.Color(0, 102, 102));
        Show1.setText("Show");
        Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show1ActionPerformed(evt);
            }
        });
        getContentPane().add(Show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 165, 75, -1));

        Show2.setForeground(new java.awt.Color(0, 102, 102));
        Show2.setText("Show");
        getContentPane().add(Show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 206, 75, -1));

        Show3.setForeground(new java.awt.Color(0, 102, 102));
        Show3.setText("Show");
        getContentPane().add(Show3, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 247, 75, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bindle_project/View/newlogo.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show1ActionPerformed
        // TODO add your handling code here:
         {
        if (Show1.isSelected()) {
            ConfirmPassword.setEchoChar((char) 0); // Show characters
        } else {
            ConfirmPassword.setEchoChar('*'); // Mask characters (use your preferred char)
        }
    }
    }//GEN-LAST:event_Show1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JPasswordField OldPassword;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Show1;
    private javax.swing.JButton Show2;
    private javax.swing.JButton Show3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
public void showpasswordButtonListener(ActionListener listener){
      Show1.addActionListener(listener);
}
public void showpasswordButtonListener1(ActionListener listener){
      Show2.addActionListener(listener);
}
public void showpasswordButtonListener2(ActionListener listener){
      Show3.addActionListener(listener);
}
public void tooglePaawordField1(boolean visible){
    ConfirmPassword.setEchoChar(visible ?(char)0:'*');
    ConfirmPassword.setText(visible ? "Hide":"Show");
}
public void tooglePaawordField2(boolean visible){
   NewPassword.setEchoChar(visible ?(char)0:'*');
    NewPassword.setText(visible ? "Hide":"Show");
}
public void tooglePaawordField3(boolean visible){
   OldPassword.setEchoChar(visible ?(char)0:'*');
    OldPassword.setText(visible ? "Hide":"Show");
}

    
}
