/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testbindleprojecct.View;

import java.awt.Font;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import testbindleprojecct.Model.Book;
import testbindleprojecct.Model.CartItem;

/**
 *
 * @author acer
 */
public class CartView extends javax.swing.JFrame {
    public JScrollPane getJScrollPane1() {
        return jScrollPane1;
    }

    public JPanel getCartItemsPanel() {
        return cartItemsPanel;
    }

    public JLabel getKafkaBookLabel() {
        return kafkaBookLabel;
    }

    public JLabel getKafkaBookTitle() {
        return kafkaBookTitle;
    }

    public JLabel getAuthorsName() {
        return authorsName;
    }

    public JLabel getIncreasingDecreasing() {
        return increasingDecreasing;
    }

    public JLabel getPriceLabel() {
        return priceLabel;
    }

   

    public JLabel getLabelShoppingCartText() {
        return labelShoppingCartText;
    }

    public JPanel getHeaderPanel() {
        return headerPanel;
    }

    public JLabel getLogoLabel() {
        return logoLabel;
    }

    public JLabel getLabelLogoTitle() {
        return labelLogoTitle;
    }

    public JLabel getLabelLogoSubTitle() {
        return labelLogoSubTitle;
    }


    

    public JLabel getLabelSearchLogo() {
        return labelSearchLogo;
    }

    public JButton getHeartButton() {
        return heartButton;
    }

  public JButton getSearchButton() {
return search;    }

    public JButton getHomeButton() {
        return homeButton;
    }
     public JButton getCheckoutButton() {
return checkoutButton; }

    /**
     * Creates new form CartView
     */
    public CartView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cartItemsPanel = new javax.swing.JPanel();
        kafkaBookLabel = new javax.swing.JLabel();
        kafkaBookTitle = new javax.swing.JLabel();
        authorsName = new javax.swing.JLabel();
        increasingDecreasing = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelShoppingCartText = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        labelLogoTitle = new javax.swing.JLabel();
        labelLogoSubTitle = new javax.swing.JLabel();
        labelSearchLogo = new javax.swing.JLabel();
        heartButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cartItemsPanel.setBackground(new java.awt.Color(255, 255, 255));
        cartItemsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        cartItemsPanel.add(kafkaBookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kafkaBookTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        kafkaBookTitle.setText("Metamorphosis");
        cartItemsPanel.add(kafkaBookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, 30));

        authorsName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        authorsName.setText("By Franz Kafka");
        cartItemsPanel.add(authorsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 100, -1));

        increasingDecreasing.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        increasingDecreasing.setText("- 1 +");
        cartItemsPanel.add(increasingDecreasing, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 70, 30));

        priceLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        priceLabel.setText("NPR. 720");
        cartItemsPanel.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 70, -1));
        cartItemsPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 190));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Intermezzo");
        cartItemsPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 100, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("By Sally Rooney");
        cartItemsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 100, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("- 1 +");
        cartItemsPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 50, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("NPR. 819");
        cartItemsPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 60, 20));

        labelShoppingCartText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelShoppingCartText.setText("Shopping Cart (n)");
        cartItemsPanel.add(labelShoppingCartText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/delete.png"))); // NOI18N
        cartItemsPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 344, 40, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/Save.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        cartItemsPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 40, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/delete.png"))); // NOI18N
        cartItemsPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 40, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/Save.png"))); // NOI18N
        cartItemsPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 40, 40));

        jScrollPane1.setViewportView(cartItemsPanel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 101, 790, 400));

        headerPanel.setLayout(null);
        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 6, -1, -1));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/newlogo_1.png"))); // NOI18N
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 55));

        labelLogoTitle.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelLogoTitle.setText("Bindle");
        getContentPane().add(labelLogoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 36));

        labelLogoSubTitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLogoSubTitle.setText("Reselling academic and non academic books ");
        getContentPane().add(labelLogoSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));
        getContentPane().add(labelSearchLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 6, -1, -1));

        heartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/mylist.png"))); // NOI18N
        getContentPane().add(heartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 60, 40));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/homeButtonImage.png"))); // NOI18N
        homeButton.setText("Home");
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 110, -1));

        checkoutButton.setText("Buy");
        getContentPane().add(checkoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 90, -1));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/SearchIcon.png"))); // NOI18N
        search.setText("Search");
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 180, -1));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorsName;
    private javax.swing.JPanel cartItemsPanel;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton heartButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel increasingDecreasing;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kafkaBookLabel;
    private javax.swing.JLabel kafkaBookTitle;
    private javax.swing.JLabel labelLogoSubTitle;
    private javax.swing.JLabel labelLogoTitle;
    private javax.swing.JLabel labelSearchLogo;
    private javax.swing.JLabel labelShoppingCartText;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables

    public void displayCartItems(List<CartItem> items) {
        cartItemsPanel.removeAll(); // Clear existing items
        if (items != null && !items.isEmpty()) {
            int yOffset = 20; // Starting Y position
            for (CartItem item : items) {
                JLabel titleLabel = new JLabel("Book ID: " + item.getBookId());
                titleLabel.setFont(new Font("Times New Roman", Font.BOLD, 18));
                cartItemsPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, yOffset, 130, 30));

                JLabel qtyLabel = new JLabel("Quantity: " + item.getQuantity());
                qtyLabel.setFont(new Font("Times New Roman", Font.PLAIN, 14));
                cartItemsPanel.add(qtyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, yOffset + 30, 100, 20));

                yOffset += 60; // Simple spacing for next item
            }
        } else {
            JLabel emptyLabel = new JLabel("Cart is empty");
            emptyLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
            cartItemsPanel.add(emptyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 20));
        }
        cartItemsPanel.revalidate();
        cartItemsPanel.repaint();
    }

   

  public void refreshCart(List<CartItem> cartItems, List<Book> books, double total) {
        displayCartItems(cartItems); // Use existing method to update items
        if (books != null && !books.isEmpty()) {
            // Update price labels or other details if needed (e.g., match books to cart items)
            // For now, update the total display (you may need to add a total label)
            labelShoppingCartText.setText("Shopping Cart (" + cartItems.size() + ") - Total: NPR. " + String.format("%.2f", total));
        }
        cartItemsPanel.revalidate();
        cartItemsPanel.repaint();
    }

    public void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    
}