/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testbindleprojecct.View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class ChangePasswordView extends javax.swing.JFrame {
 
    /**
     * Creates new form hangePasswordView
     */
    public ChangePasswordView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NewPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        OldPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JPasswordField();
        save = new javax.swing.JButton();
        Show2 = new javax.swing.JButton();
        Show3 = new javax.swing.JButton();
        Show1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Change Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 67, 245, -1));

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 172, -1, -1));
        getContentPane().add(NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 169, 188, -1));

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Old Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 131, 79, -1));
        getContentPane().add(OldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 128, 189, -1));

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 214, -1, -1));
        getContentPane().add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 207, 188, -1));

        save.setBackground(new java.awt.Color(0, 102, 102));
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 257, 75, -1));

        Show2.setText("Show");
        getContentPane().add(Show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 169, -1, -1));

        Show3.setText("Show");
        getContentPane().add(Show3, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 207, -1, -1));

        Show1.setText("Show");
        Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show1ActionPerformed(evt);
            }
        });
        getContentPane().add(Show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 128, -1, -1));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 68, 60, 40));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 33, -1, -1));

        cancel.setText("Cancel");
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 257, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Show1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePasswordView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JPasswordField OldPassword;
    private javax.swing.JButton Show1;
    private javax.swing.JButton Show2;
    private javax.swing.JButton Show3;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

    
    // Getter methods for components
    public JLabel getTitleLabel() {
        return jLabel1;
    }

    public JLabel getNewPasswordLabel() {
        return jLabel2;
    }

    public javax.swing.JPasswordField getNewPasswordField() {
        return NewPassword;
    }

    public JLabel getOldPasswordLabel() {
        return jLabel3;
    }

    public javax.swing.JPasswordField getOldPasswordField() {
        return OldPassword;
    }

    public JLabel getConfirmPasswordLabel() {
        return jLabel4;
    }

    public javax.swing.JPasswordField getConfirmPasswordField() {
        return ConfirmPassword;
    }

    public JButton getSaveButton() {
        return save;
    }
    public JButton getCancelButton() {
        return cancel;
    }
    

    public JButton getShow1Button() {
        return Show1;
    }

    public JButton getShow2Button() {
        return Show2;
    }

    public JButton getShow3Button() {
        return Show3;
    }

    // Existing main method and variable declarations remain unchanged
    // ... (omitted for brevity)
      public void showPasswordButtonListener1(ActionListener listener) {
        Show1.addActionListener(listener);
    }

    public void tooglePasswordField1(boolean visible) {
        OldPassword.setEchoChar(visible ? (char) 0 : '*');
        Show1.setText(visible ? "Hide" : "Show");
    }
  public void showPasswordButtonListener2(ActionListener listener) {
        Show2.addActionListener(listener);
    }

    public void tooglePasswordField2(boolean visible) {
        NewPassword.setEchoChar(visible ? (char) 0 : '*');
        Show2.setText(visible ? "Hide" : "Show");
    }
      public void showPasswordButtonListener3(ActionListener listener) {
        Show3.addActionListener(listener);
    }

    public void tooglePasswordField3(boolean visible) {
        ConfirmPassword.setEchoChar(visible ? (char) 0 : '*');
        Show3.setText(visible ? "Hide" : "Show");
    }
}
