/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testbindleprojecct.View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class HomeView extends javax.swing.JFrame {
 
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelLogoTitle = new javax.swing.JLabel();
        labelLogoSubTitle = new javax.swing.JLabel();
        labelBooks = new javax.swing.JLabel();
        labelForAll = new javax.swing.JLabel();
        labelShopNow = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        sell = new javax.swing.JButton();
        HeartButton = new javax.swing.JButton();
        CartButton = new javax.swing.JButton();
        availablebooks = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/HomeScreenBookshelf.png"))); // NOI18N
        jLabel1.setText("Search");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 125, 310, 360));

        labelLogoTitle.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelLogoTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/newlogo_1.png"))); // NOI18N
        labelLogoTitle.setText("Bindle");
        getContentPane().add(labelLogoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, 200, 50));

        labelLogoSubTitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLogoSubTitle.setText("Reselling academic and non academic books ");
        getContentPane().add(labelLogoSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, 280, -1));

        labelBooks.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelBooks.setText("B00KS");
        getContentPane().add(labelBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 172, 210, 50));

        labelForAll.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelForAll.setText("F0R ALL");
        getContentPane().add(labelForAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 228, 250, -1));

        labelShopNow.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labelShopNow.setText("SHOP NOW");
        labelShopNow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        labelShopNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelShopNowMouseClicked(evt);
            }
        });
        getContentPane().add(labelShopNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 326, 140, 50));

        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/SearchIcon.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 140, 37));

        Logout.setText("LogOut");
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        profile.setText("Profile");
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 75, -1));

        sell.setText("Sell");
        sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellActionPerformed(evt);
            }
        });
        getContentPane().add(sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 75, 40));

        HeartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/mylist.png"))); // NOI18N
        HeartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HeartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 53, 40));

        CartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/CART.png"))); // NOI18N
        getContentPane().add(CartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 57, 40));

        availablebooks.setText("Available books");
        getContentPane().add(availablebooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelShopNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelShopNowMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelShopNowMouseClicked

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonMouseClicked

    private void sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellActionPerformed

    private void HeartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CartButton;
    private javax.swing.JButton HeartButton;
    private javax.swing.JButton Logout;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton availablebooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBooks;
    private javax.swing.JLabel labelForAll;
    private javax.swing.JLabel labelLogoSubTitle;
    private javax.swing.JLabel labelLogoTitle;
    private javax.swing.JLabel labelShopNow;
    private javax.swing.JButton profile;
    private javax.swing.JButton sell;
    // End of variables declaration//GEN-END:variables

    // Getter methods for components
  

    public JLabel getTitleLabel() {
        return labelLogoTitle;
    }

    public JLabel getSubTitleLabel() {
        return labelLogoSubTitle;
    }

    public JLabel getBooksLabel() {
        return labelBooks;
    }

    public JLabel getForAllLabel() {
        return labelForAll;
    }

    public JLabel getShopNowLabel() {
        return labelShopNow;
    }

    public JButton getSearchButton() {
        return SearchButton;
    }

    public JButton getLogoutButton() {
        return Logout;
    }

    public JButton getProfileButton() {
        return profile;
    }

    public JButton getSellButton() {
        return sell;
    }

    public JButton getHeartButton() {
        return HeartButton;
    }

    public JButton getCartButton() {
        return CartButton;
    }

    public JButton getAvailableBooksButton() {
        return availablebooks;
    }

    // Existing main method and variable declarations remain unchanged
    // ... (omitted for brevity)

}
