/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testbindleprojecct.View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class RegisterView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterView
     */
    public RegisterView() {
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        RegisterButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        show1 = new javax.swing.JButton();
        show2 = new javax.swing.JButton();
        AlreadyHaveAnAccount = new javax.swing.JLabel();
        sendOtp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        OtpTextfield = new javax.swing.JTextField();
        verify = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterButton.setBackground(new java.awt.Color(204, 102, 255));
        RegisterButton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        getContentPane().add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 200, 40));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Create an account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 15, 300, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 67, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 90, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 160, -1));

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 350, 40));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 350, 40));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 350, 40));

        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 350, 40));

        show1.setText("Show");
        getContentPane().add(show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, 30));

        show2.setText("Show");
        getContentPane().add(show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, -1, 30));

        AlreadyHaveAnAccount.setText("Already Have an Account?");
        getContentPane().add(AlreadyHaveAnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, -1, -1));

        sendOtp.setText("Send OTP");
        getContentPane().add(sendOtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, -1, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Enter OTP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));
        getContentPane().add(OtpTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 270, 40));

        verify.setText("Verify");
        getContentPane().add(verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testbindleprojecct/images/RegisterBackground.png"))); // NOI18N
        logo.setText("jLabel7");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 940, 630));

        background.setText("jLabel6");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 0, 0, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlreadyHaveAnAccount;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField OtpTextfield;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton sendOtp;
    private javax.swing.JButton show1;
    private javax.swing.JButton show2;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables
public JButton getRegisterButton() {
        return RegisterButton;
    }

    public JLabel getLogoLabel() {
        return logo;
    }

    public JLabel getTitleLabel() {
        return jLabel1;
    }

    public JLabel getNameLabel() {
        return jLabel2;
    }

    public JLabel getEmailLabel() {
        return jLabel3;
    }

    public JLabel getPasswordLabel() {
        return jLabel4;
    }

    public JLabel getConfirmPasswordLabel() {
        return jLabel5;
    }

    public JTextField getNameField() {
        return Name;
    }

    public JTextField getEmailField() {
        return Email;
    }

    public JPasswordField getPasswordField() {
        return password;
    }

    public JPasswordField getConfirmPasswordField() {
        return ConfirmPassword;
    }

    public JButton getShow1Button() {
        return show1;
    }

    public JButton getShow2Button() {
        return show2;
    }

    public JLabel getAlreadyHaveAnAccountLabel() {
        return AlreadyHaveAnAccount;
    }

   public javax.swing.JTextField getOtpField() {
        return OtpTextfield;
    }

    public javax.swing.JButton getVerifyButton() {
        return verify;
    }

    public void setOtpFieldVisible(boolean visible) {
        OtpTextfield.setVisible(visible);
    }

    public void setVerifyButtonVisible(boolean visible) {
        verify.setVisible(visible);
    }
    public javax.swing.JButton getSendOtpButton() {
        return sendOtp;
    }

    public void setSendOtpButtonVisible(boolean visible) {
        sendOtp.setVisible(visible);
    
    }
    public void addRegisterListener(ActionListener listener){
    RegisterButton.addActionListener(listener);}
    
    public void showPasswordButtonListener(ActionListener listener){
show1.addActionListener(listener);}
public void tooglePasswordField(boolean visible){
password.setEchoChar(visible ? (char) 0:'*');
show1.setText(visible ? "Hide":"Show");}
public void showPasswordButtonListener1(ActionListener listener){
show2.addActionListener(listener);}
public void tooglePasswordField1(boolean visible){
ConfirmPassword.setEchoChar(visible ? (char) 0:'*');
show2.setText(visible ? "Hide":"Show");}
    
}
