/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BindleFrame;

/**
 *
 * @author ACER
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogo = new javax.swing.JLabel();
        labelCartIcon = new javax.swing.JLabel();
        labelHeartIcon = new javax.swing.JLabel();
        labelSearchLogo = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelLogoTitle = new javax.swing.JLabel();
        labelLogoSubTitle = new javax.swing.JLabel();
        labelBooks = new javax.swing.JLabel();
        labelForAll = new javax.swing.JLabel();
        labelShopNow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/BindleBook.png"))); // NOI18N
        labelLogo.setText("jLabel1");
        getContentPane().add(labelLogo);
        labelLogo.setBounds(6, 28, 62, 40);

        labelCartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/Cart.png"))); // NOI18N
        labelCartIcon.setText("jLabel2");
        getContentPane().add(labelCartIcon);
        labelCartIcon.setBounds(540, 30, 53, 30);

        labelHeartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/Heart.png"))); // NOI18N
        labelHeartIcon.setText("jLabel3");
        getContentPane().add(labelHeartIcon);
        labelHeartIcon.setBounds(510, 30, 30, 30);

        labelSearchLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/SearchIcon.png"))); // NOI18N
        labelSearchLogo.setText("jLabel4");
        getContentPane().add(labelSearchLogo);
        labelSearchLogo.setBounds(260, 30, 37, 30);

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchTextField);
        searchTextField.setBounds(260, 30, 240, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bindle_Images/HomeScreenBookshelf.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 60, 310, 400);

        labelLogoTitle.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelLogoTitle.setText("Bindle");
        getContentPane().add(labelLogoTitle);
        labelLogoTitle.setBounds(80, 20, 200, 50);

        labelLogoSubTitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLogoSubTitle.setText("Reselling academic and non academic books ");
        getContentPane().add(labelLogoSubTitle);
        labelLogoSubTitle.setBounds(80, 60, 280, 17);

        labelBooks.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelBooks.setText("B00KS");
        getContentPane().add(labelBooks);
        labelBooks.setBounds(40, 170, 210, 50);

        labelForAll.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelForAll.setText("F0R ALL");
        getContentPane().add(labelForAll);
        labelForAll.setBounds(40, 210, 250, 56);

        labelShopNow.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labelShopNow.setText("SHOP NOW");
        labelShopNow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        labelShopNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelShopNowMouseClicked(evt);
            }
        });
        getContentPane().add(labelShopNow);
        labelShopNow.setBounds(40, 270, 140, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        
        BookGridScreen bookGrid = new BookGridScreen();
        bookGrid.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void labelShopNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelShopNowMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelShopNowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBooks;
    private javax.swing.JLabel labelCartIcon;
    private javax.swing.JLabel labelForAll;
    private javax.swing.JLabel labelHeartIcon;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelLogoSubTitle;
    private javax.swing.JLabel labelLogoTitle;
    private javax.swing.JLabel labelSearchLogo;
    private javax.swing.JLabel labelShopNow;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
